
GET http://127.0.0.1:3000/producto



### guardar
POST http://127.0.0.1:3000/producto
Content-Type: application/json

{
    "nombre": "monescritorii",
    "estado": false,
    "precio": 500
}


### mostrar
GET http://127.0.0.1:3000/producto/3


### modificar

PATCH http://127.0.0.1:3000/producto/2
Content-Type: application/json

{
    "nombre": "prueba"
}

### eliminar

DELETE http://127.0.0.1:3000/producto/1

